### PR TITLE
Update m4

### PR DESCRIPTION
**Pull request by mattst88**
Split from https://github.com/ibus/ibus/pull/2523/

### CODE REVIEW

**Comment by fujiwarat** [comment]
Thank you for the patch. I modified .gitignore.

**Comment by mattst88** [comment]
> BUG=https://github.com/ibus/ibus/pull/2527

If you just use "Closes: ..." (or any of the other keywords, see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) Github will automatically link the commit to the merge request.

**Comment by mattst88** [comment]
> Thank you for the patch. I modified .gitignore.

And now you have all of these files listed in `git status` after running `autogen.sh`.

````
	m4/codeset.m4
	m4/extern-inline.m4
	m4/fcntl-o.m4
	m4/gettext.m4
	m4/glibc2.m4
	m4/glibc21.m4
	m4/gtk-doc.m4
	m4/iconv.m4
	m4/intdiv0.m4
	m4/intl.m4
	m4/intldir.m4
	m4/intlmacosx.m4
	m4/intmax.m4
	m4/inttypes-pri.m4
	m4/inttypes_h.m4
	m4/lcmessage.m4
	m4/lib-ld.m4
	m4/lib-link.m4
	m4/lib-prefix.m4
	m4/libtool.m4
	m4/lock.m4
	m4/longlong.m4
	m4/ltoptions.m4
	m4/ltsugar.m4
	m4/ltversion.m4
	m4/lt~obsolete.m4
	m4/nls.m4
	m4/po.m4
	m4/printf-posix.m4
	m4/progtest.m4
	m4/size_max.m4
	m4/stdint_h.m4
	m4/threadlib.m4
	m4/uintmax_t.m4
	m4/visibility.m4
	m4/wchar_t.m4
	m4/wint_t.m4
	m4/xsize.m4
````

**Comment by fujiwarat** [comment]
> > BUG=#2527
> 
> If you just use "Closes: ..." (or any of the other keywords, see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) Github will automatically link the commit to the merge request.

I expect the full URL in git log but not the link on github.
I have used BUG=URL for the back compatibility since IBus had used codereview.appspot.com with codereview.settings file.

**Comment by fujiwarat** [comment]
> > Thank you for the patch. I modified .gitignore.
> 
> And now you have all of these files listed in `git status` after running `autogen.sh`.

Right. I think adding *.m4 in .gitignore file is not good to add new m4 files. I wonder if GITIGNOREFILES in m4/Makefile.am could effect something.

**Comment by mattst88** [comment]
> I expect the full URL in git log but not the link on github.

That's how it works. See the `Closes:` link in 

https://github.com/gentoo/gentoo/commit/3ec6df9dd35b114f4aaf4aeb782f93388884ad2e (on github)

vs

https://github.com/gentoo/gentoo/commit/3ec6df9dd35b114f4aaf4aeb782f93388884ad2e.patch (in git log)

**Comment by fujiwarat** [comment]
Thank you. I will consider it later.

**Pull request closed without merging**
