### PR TITLE
Replace Bengali with Bangla

### LINKED ISSUE #2104: Replace Bengali with Bangla
IBus input methods for inputting Bangla are currently presented to the users with "Bengali" instead of "Bangla" in the GUIs. This applies to the Bangla IMs in ibus-m17n, but also to e.g. ibus-avro.

The explanation is that ISO has still not changed the name officially, which is reflected in the `iso_639.xml` file from which the languages are fetched. However, since most upstream resources use the modern name Bangla nowadays, `iso_639.xml` also states a "common_name" field with the value "Bangla" for the "bn" language code.

Ideally the parsing of `iso_639.xml` should pick the "common_name" value if present or else the "name" value. That's not the approach I'm using in the pull request I'm about to submit. It's a hack. Possibly it's still acceptable, considering that "bn" is the only language code in `iso_639.xml` for which the "common_name" field is used.

Some background to this request can be found in [this umbrella Ubuntu bug](https://launchpad.net/bugs/991002).

### PR DESCRIPTION
**Pull request by gunnarhj**
Fixes #2104

### CODE REVIEW

**Comment by gunnarhj** [comment]
Ok.. I'm not much of a programmer, but I can copy and paste, and gave it a try.

**Comment by fujiwarat** [comment]
Thank you for the patch. I don't prefer having two for-loops and I created another patch.

**Comment by gunnarhj** [comment]
@fujiwarat: Which was a better solution and shows my lack of coding skill. Thanks for the lesson and for responding to this so fast!

**Comment by fujiwarat** [comment]
Your patch was useful to understand the desired fix and what was difficult for you so I will ask you to submit patches if you can.

**Pull request closed without merging**
