### PR TITLE
Add Uzbek layouts

### PR DESCRIPTION
**Pull request by bmansurov**
It wasn't clear whether I should be adding these input methods manually or by using gensimple.py, which seems to get the list of entries from some URL.

### CODE REVIEW

**Comment by fujiwarat** [comment]
gensimple.py is no longer used since the whitelist is too narrow.
I just have one question. Are the uz-cyrillic and uz-latin important to be shown on ibus-setup by default?

**Comment by bmansurov** [comment]
@fujiwarat do you mean to show it under "Input Method" tab and "Add" button, as shown in the screenshot?
ibus-langlist

I'd say yes because both scripts are in active use in the Uzbek language.

**Comment by fujiwarat** [comment]
I meant the former question and thank you for the reply.
My last question is your email address is ... at users.noreply.github.com ? If not, plese re-submit it again.

**Comment by bmansurov** [comment]
@fujiwarat yes, that's my email on Github. Let's go with it.

**Comment by fujiwarat** [comment]
Sorry, I still have a question.
You try to add `xkb:uz:cyrillic:uzb` and `xkb:uz:latin:uzb` but why don't you add `xkb:uz::uzb`?

I will modify to delete non English sentence.  E.g. s/Uzbek Latin (Oʻzbekcha)/Uzbek Latin/ to follow `/usr/share/X11/xkb/rules/evdev.xml` and the translation is available in `xkeyboard-config` package.
I will replace rank 99 with 1 for the layout + variant keymaps.

**Comment by bmansurov** [comment]
I didn't know that xkb:uz::uzb would work. If it does, then please feel free to add it instead of the other two. I was just trying to follow the other entries in the file.

Sure, make any other change you think is necessary. Thanks!

**Comment by fujiwarat** [comment]
I was a bit busy for other tasks and committed now.

**Comment by bmansurov** [comment]
Thanks!

**Pull request closed without merging**
