### PR TITLE
Constrain the candidate area to the current monitor bounds

### LINKED ISSUE #1594: ibus popup menu does not *seem* to respect xinerama
```
OS (Linux distributions, UNIX or ...): Ubuntu 12.04.1 LTS
Architecture (i386, x86_64): x86_64
IBus version: 1.4.1
Input method name and version: IBus-Anthy 1.2.6
Python version: 2.7.3
dbus version: 1.4.18
dbus-python version: (unknown)
gtk version (if bug is about gtk applications): (Gnome-terminal, probably gtk 3)

What steps will reproduce the problem?
1. Set up dual monitor, with different resolution (1680x1050 and 1920x1080) with the
top aligned, IE so there's a gap on the bottom of the 1680x1050
2. Fullscreen gnome-terminal on the smaller monitor (1680x1050)
3. Run irssi, input should be on bottom row of gnome-terminal
4. enter ibus-anthy and type something, say "わたし" then press space to change it to
kanji then use the up/down arrows to bring up a menu for selecting which one to convert
to.
5. The menu is displaying below the input field, we can now only see a couple of pixels
on screen, the rest is off screen.

What is the expected output?

The expected output is for the menu to display *above* the word being converted, this
works properly on the (1920x1080) monitor, so it seems to indicate some form of xinerama
issue with ibus menu dropdown.
```

Original issue reported on code.google.com by `pharaun666` on 2013-01-15 23:00:55

### PR DESCRIPTION
**Pull request by koterpillar**
Fixes #1594.

### CODE REVIEW

**Comment by koterpillar** [comment]
I have only tested this with the Gtk3 UI, works as expected.

**Comment by fujiwarat** [comment]
Thanks for the patch.
Now I can test the double monitor and understand the problem.

+        int monitor = screen.get_monitor_at_point(cursor_right_bottom.x,
+                                                  cursor_right_bottom.y);

Probably I prefer m_cursor_location.[x|y] to cursor_right_bottom.[x|y] in adjust_window_position_horizontal() and adjust_window_position_vertical().
Other things look good.

One concern is that monitor_area.height is a little smaller than the actual monitor height with a small bottom panel dock likes XFCE. But it's ok with me.

**Comment by koterpillar** [comment]
If you want, I can use `get_monitor_geometry` instead of `get_monitor_workarea` which does not take docks into account.

Changed `cursor_right_bottom` to `cursor_location`.

**Comment by fujiwarat** [comment]
```
+        int monitor_num = screen.get_monitor_at_point(cursor_right_bottom.x,
+                                                      cursor_right_bottom.y);
```
adjust_window_position_vertical() is also good to be changed.

> If you want, I can use get_monitor_geometry instead of get_monitor_workarea which does not take docks into account.

Yeah, I prefer it since lookup window is always shown over the docks.

**Comment by koterpillar** [comment]
All changed.

**Comment by fujiwarat** [comment]
https://github.com/ibus/ibus/commit/4a8024b0a3e5670dc5ad88a26b90b0a9801efcca

**Pull request closed without merging**
