### PR TITLE
Minor tweaks to org.freedesktop.IBus.session.generic.service and org.freedesktop.IBus.session.GNOME.service

### PR DESCRIPTION
**Pull request by simondeziel**

### CODE REVIEW

**Comment by simondeziel** [comment]
`exec` is to avoid keeping the parent process around by telling the shell to replace itself by the child process.
You can easily check it with `ps faux` while comparing `/bin/sh -c 'sleep 300'` to `/bin/sh -c 'exec sleep 300'`.

As for the generic session, since the ExecStart is directly calling a single binary, I don't see what using `sh` around provides?

**Comment by simondeziel** [comment]
I don' think the distro should matter but maybe? Anyway, here's what it looks like on Ubuntu:

```
$ /bin/sh -c 'sleep 300' & ps faux | grep -B2 'sleep 300'
[1] 2690547
sdeziel  2689640  0.0  0.0  20200  5692 pts/4    Ss+  12:39   0:00  |   \_ /bin/bash
sdeziel  2689658  0.0  0.0  20192  5728 pts/6    Ss   12:39   0:00  |   \_ /bin/bash
sdeziel  2690547  0.0  0.0   2888   976 pts/6    S    12:40   0:00  |       \_ /bin/sh -c sleep 300
sdeziel  2690550  0.0  0.0  17024  1048 pts/6    S    12:40   0:00  |       |   \_ sleep 300
sdeziel  2690548  0.0  0.0  21448  3576 pts/6    R+   12:40   0:00  |       \_ ps faux
sdeziel  2690549  0.0  0.0  17732  2292 pts/6    S+   12:40   0:00  |       \_ grep --color=auto -B2 sleep 300
```

We see above there is a `/bin/sh -c sleep 300` process hanging around. And now with exec:

```
$ /bin/sh -c 'exec sleep 300' & ps faux | grep -B2 'sleep 300'
[1] 2690623
sdeziel  2689640  0.0  0.0  20200  5692 pts/4    Ss+  12:39   0:00  |   \_ /bin/bash
sdeziel  2689658  0.0  0.0  20192  5728 pts/6    Ss   12:39   0:00  |   \_ /bin/bash
sdeziel  2690623  0.0  0.0  17024  1020 pts/6    S    12:40   0:00  |       \_ sleep 300
sdeziel  2690624  0.0  0.0  21448  3472 pts/6    R+   12:40   0:00  |       \_ ps faux
sdeziel  2690625  0.0  0.0  17732  2304 pts/6    S+   12:40   0:00  |       \_ grep --color=auto -B2 sleep 300
```

The `sleep` command replaced the `/bin/sh -c sleep 300` so there is no unneeded process left around.

**Comment by fujiwarat** [comment]
> We see above there is a /bin/sh -c sleep 300 process hanging around. And now with exec:

Sorry, what do you mean that process hanging around? I don't see any hanging processes.

**Comment by simondeziel** [comment]
Sorry, by "hanging around" I meant that it stayed around, not literally be hung or stuck.

**Comment by fujiwarat** [comment]
Maybe I still notice your issue.
My result in Fedora 37 x86_64 and I don't see your parent sh process:
```
#  /bin/sh -c 'sleep 300' & ps faux | grep -B2 'sleep 300'
[1] 1475
root        1445  1.5  0.7 233768  7828 pts/0    S    12:00   0:00              \_ su -
root        1446  0.3  0.5 224632  5760 pts/0    S    12:00   0:00                  \_ -bash
root        1475  0.0  0.0 221320   944 pts/0    S    12:00   0:00                      \_ sleep 300
root        1476  0.0  0.3 224636  3576 pts/0    R+   12:00   0:00                      \_ ps faux
root        1477  0.0  0.2 222032  2424 pts/0    S+   12:00   0:00                      \_ grep --color=auto -B2 sleep 300
```

Curious if Fedora and Ubuntu would have the different results.

**Comment by simondeziel** [comment]
Wow, I really didn't expect this, thanks for showing!

**Comment by fujiwarat** [comment]
Hmm.., Fedora and Ubuntu have different sh?
Fedora sh is bash.
```
# ls -l /bin/sh
lrwxrwxrwx. 1 root root 4 Nov 18 23:27 /bin/sh -> bash
#  rpm -q bash
bash-5.2.9-3.fc37.x86_64
```

**Comment by simondeziel** [comment]
On Ubuntu, it's `dash`:

```
$ ll /bin/sh
lrwxrwxrwx 1 root root 4 Sep 10 16:02 /bin/sh -> dash*
```

**Comment by fujiwarat** [comment]
Can your problem be fixed if you replace sh with bash in the service file?

**Comment by fujiwarat** [comment]
Also what is the parent process with your issue?
The parent process is systemd in Fedora 37 x86_64:
```
root       1367  0.0  0.2  22940  2548 ?        Ss   Jan17   0:01 /usr/lib/systemd/systemd --user
root      86582  0.0  0.5 528332  5148 ?        Ssl  09:24   0:00  \_ /usr/bin/ibus-daemon --panel disable
```

**Comment by fujiwarat** [comment]
Any responses?

**Comment by simondeziel** [comment]
This PR is not fixing any problem, it merely tries to be "cleaner".

For the GNOME one, using `exec` avoid keep a `sh` process around, no mater what `/bin/sh` points to.

For the generic one, you said:

> sh extracts the arguments of ibus-daemon and should be used.

I just noticed the `S` in `IBUS_DAEMON_ARGS` so that's probably why the shell wrapper is needed. I've updated the PR accordingly.

**Comment by fujiwarat** [comment]
You don't answer my questions but I accept your patch.

> I just noticed the S in IBUS_DAEMON_ARGS 

The location of the service file can be fallen back into the user home directory and users can customize the environment variables.

**Comment by simondeziel** [comment]
> You don't answer my questions

Oh sorry, that was not my intention. Re `dash` vs `bash`, they behave differently when provided with a simple command. In this case, I /think/ using `bash` would work.

> but I accept your patch.

Thanks!

**Pull request closed without merging**
