### PR TITLE
client/gtk2: Capture the key event with GtkEventControllerKey

### PR DESCRIPTION
**Pull request by epico**
Related URL: https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/320

### CODE REVIEW

**Review by fujiwarat — COMMENTED** [review]
Thank you for the patch.
I think this way change lets ibus receive key events earlier than gtksourceview and it's convenient for ibus but probably gtksourceview don't agree with it.

From the bug comments:
```
Takao Fujiwara @fujiwarat · [3 months ago](https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/320#note_1742764) Author
Would you please elaborate the example why gtksourceview needs any keys to trigger indentation operation? I'd like to resolve your issues too.

Christian Hergert @chergert · [3 months ago](https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/320#note_1743427) Maintainer
GtkSourceIndenter can be implemented by applications to do whatever per-programming-language features they need. Some languages benefit from auto-indenting a line based on specific input which includes alphabet keys.

At one point, there was a python indenter in Builder that would unindent a line as soon as you typed else or elif matching the if block.

In addition to that, GtkSourceCompletionProvider can trigger activation automatically based on the input such as things like C may trigger a field completion when - or . is pressed. But other programming languages may complete on other input characters.

In the Language Server Protocol, it's quite arbitrary what can cause a completion proposal to be inserted and also must be inserted before the text is applied.

Takao Fujiwara @fujiwarat · [2 months ago](https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/320#note_1748032) Author
I'm thinking GtkIMContext should commit the ASCII keys. With Wayland input-method protocol, IBus tries to switch XKB internally upon the user request and calculates keysyms from keycodes with the specified layout and the applications cannot know the current keysyms although GNOME Wayland does not provide the input-method protocol. And also some IBus input method engines commit different keysyms against the received keysyms or have an ability of a prediction. E.g. if a user types "el" and commits "else".
The current my idea is:

GtkSourceView receives a key
GtkSourceView remembers the current GtkTextBuffer
GtkSourceView sends it to gtk_text_view_im_context_filter_keypress()
GtkSourceView receives TRUE from gtk_text_view_im_context_filter_keypress()
GtkSourceView compares the updated GtkTextBuffer with and the remembered GtkTextBuffer and if ASCII was committed GtkSourceView calculate the auto-indent.

I also think the similar idea with you however I think exporting the commit signal from GtkTextView might be enough.
Sorry, currently I'm working on other tasks and I'll investigate GtkSourceView again later.
```

If ibus receives key events earlier than gtksourceview in any keys, gtksourceview cannot check ASCII keys because ibus commit them and return TRUE.

So probably I think your patch is better for ibus to fix the original issue but would cause a regression in gtksourceview.
This is the first concern.

And I think your patch causes two key releases by one key press.
The first key release is called with phase=GTK_PHASE_CAPTURE in gtk_widget_run_controllers():
```
#0  _process_key_event
    (context=0x55ba52b09020, event=0x55ba4d797a10, ibusimcontext=0x55ba52a85880) at ibus-1.5.28/client/gtk4/ibusimcontext.c:635
#1  0x00007f506803ceb5 in ibus_im_context_filter_keypress
    (context=0x55ba52a85880, event=0x55ba4d797a10)
    at ibus-1.5.28/client/gtk4/ibusimcontext.c:1347
#2  0x00007f506b9dcdbe in gtk_im_context_filter_keypress
    (context=0x55ba52a85880, key=0x55ba4d797a10) at ../gtk/gtkimcontext.c:533
#3  0x00007f506b97954e in gtk_event_controller_key_handle_event
    (controller=0x55ba52a77c20, event=0x55ba4d797a10, x=0, y=0)
    at ../gtk/gtkeventcontrollerkey.c:99
#4  0x00007f506b9780af in gtk_event_controller_handle_event
    (controller=0x55ba52a77c20, event=0x55ba4d797a10, target=0x55ba4d5104a0, x=0, y=0) at ../gtk/gtkeventcontroller.c:362
#5  0x00007f506bb3cc63 in gtk_widget_run_controllers
    (widget=0x55ba4d5104a0, event=0x55ba4d797a10, target=0x55ba4d5104a0, x=0, y=0, phase=GTK_PHASE_CAPTURE) at ../gtk/gtkwidget.c:4565
```

The second key release is called with phase=GTK_PHASE_BUBBLE in gtk_widget_run_controllers():
```
#0  _process_key_event
    (context=0x55ba52b09020, event=0x55ba4d797a10, ibusimcontext=0x55ba52a85880) at ibus-1.5.28/client/gtk4/ibusimcontext.c:635
#1  0x00007f506803ceb5 in ibus_im_context_filter_keypress
    (context=0x55ba52a85880, event=0x55ba4d797a10)
    at ibus-1.5.28/client/gtk4/ibusimcontext.c:1347
#2  0x00007f506b9dcdbe in gtk_im_context_filter_keypress
    (context=0x55ba52a85880, key=0x55ba4d797a10) at ../gtk/gtkimcontext.c:533
#3  0x00007f506b9e2276 in gtk_im_multicontext_filter_keypress
    (context=0x55ba4d511830, event=0x55ba4d797a10)
    at ../gtk/gtkimmulticontext.c:379
#4  0x00007f506b9dcdbe in gtk_im_context_filter_keypress
    (context=0x55ba4d511830, key=0x55ba4d797a10) at ../gtk/gtkimcontext.c:533
#5  0x00007f506b97954e in gtk_event_controller_key_handle_event
    (controller=0x55ba4d512650, event=0x55ba4d797a10, x=0, y=0)
    at ../gtk/gtkeventcontrollerkey.c:99
#6  0x00007f506b9780af in gtk_event_controller_handle_event
    (controller=0x55ba4d512650, event=0x55ba4d797a10, target=0x55ba4d5104a0, x=0, y=0) at ../gtk/gtkeventcontroller.c:362
#7  0x00007f506bb3cc63 in gtk_widget_run_controllers
    (widget=0x55ba4d5104a0, event=0x55ba4d797a10, target=0x55ba4d5104a0, x=0, y=0, phase=GTK_PHASE_BUBBLE) at ../gtk/gtkwidget.c:4565
```

This is the second concern.

**Comment by epico** [comment]
Thanks for the information!

I think I need to move this patch from ibus to gtk4.

URL: https://pwu.fedorapeople.org/ibus/gtk/gtk4-im-key-controller.patch

Any comments on the new patch?

**Comment by epico** [comment]
Sorry, let me test this patch again.

**Comment by epico** [comment]
I think maybe we also need to add another patch.

URL: https://pwu.fedorapeople.org/ibus/gtk/gtksourceview-im-key-control.patch

The basic idea is to use GTK_PHASE_CAPTURE for input method, and use GTK_PHASE_BUBBLE for GtkSourceView.

**Comment by fujiwarat** [comment]
> The basic idea is to use GTK_PHASE_CAPTURE for input method, and use GTK_PHASE_BUBBLE for GtkSourceView.

That change was my original suggestion while I'm not sure what is another patch against gtksourceview. The gtksourceview-maintainer won't agree with it if we change the key receiving order simply.
As I forwarded the upstream report, my current idea is
```
GtkSourceView receives a key
GtkSourceView remembers the current GtkTextBuffer
GtkSourceView sends it to gtk_text_view_im_context_filter_keypress()
GtkSourceView receives TRUE from gtk_text_view_im_context_filter_keypress()
GtkSourceView compares the updated GtkTextBuffer with and the remembered GtkTextBuffer and if ASCII was committed GtkSourceView calculate the auto-indent.
```
I think the idea can be done with your gtk_text_get_im_key_controller().

Of course, it would be great if we could fix the original issue with ibus changes only.

**Comment by epico** [comment]
Actually I think your new proposal has similar code logic like GtkEventControllerKey.

And for ibus-hangul, you may need to check the commit when receives FALSE from gtk_text_view_im_context_filter_keypress function I guess.

**Comment by epico** [comment]
I think GtkEventControllerKey will call gtk_im_context_filter_keypress function internally.

**Comment by fujiwarat** [comment]
> And for ibus-hangul, you may need to check the commit when receives FALSE from gtk_text_view_im_context_filter_keypress function I gues

Not sure why you indicate ibus-hangul and checking return value is not enough as I explained.

**Comment by fujiwarat** [comment]
gktsourceview is fixed in upstream.

**Pull request closed without merging**
